name: PHP Tests
on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: "PHP-${{ matrix.php-versions }}: PHPUnit"
    strategy:
      matrix:
        php-versions: ['7.4']
        experimental: [false]
        include:
          - php-versions: 8.0
            experimental: true
          - php-versions: 8.1
            experimental: true
          - php-versions: 8.2
            experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: uopz
          tools: phpunit

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer install

      - name: Setup fake certificates
        run: |
          touch entrust_root_certification_authority.pem
          touch server_certificates_bundle_sandbox.pem

      - name: Run PHPUnit
        run: phpunit -c phpunit.xml

  sample_push:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: "PHP-${{ matrix.php-versions }}: Sample"
    strategy:
      matrix:
        php-versions: ['7.4']
        experimental: [false]
        include:
          - php-versions: 8.0
            experimental: true
          - php-versions: 8.1
            experimental: true
          - php-versions: 8.2
            experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: uopz

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Install dependencies
        run: composer install

      - name: Setup fake certificates
        run: |
          touch entrust_root_certification_authority.pem
          touch server_certificates_bundle_sandbox.pem

      - name: Run sample
        run: php sample_push.php | grep "Trying to initialize HTTP/2 backend"

  phpcs:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: "PHPCS"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHPCS
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: cs2pr, phpcs

      - name: Run PHPCS
        run: phpcs -q --report=checkstyle ApnsPHP | cs2pr

  phpstan:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: "PHPStan"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHPStan
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phpstan
          extensions: uopz

      - name: Install dependencies
        run: composer install

      - name: Run PHPStan
        run: phpstan analyse ApnsPHP -l0
